"""empty message

Revision ID: 1ca916a89d8b
Revises: 622943a100a2
Create Date: 2025-01-04 18:22:10.144249

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ca916a89d8b"
down_revision: Union[str, None] = "622943a100a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_update",
        sa.Column("last_earn_daily", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "user_update",
        sa.Column("last_earn_debit_card", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_column("user_update", "last_used_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_update",
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user_update", "last_earn_debit_card")
    op.drop_column("user_update", "last_earn_daily")
    # ### end Alembic commands ###
