"""empty message

Revision ID: 223462abd4c0
Revises: 610a0633a584
Create Date: 2024-12-29 18:12:38.374277

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "223462abd4c0"
down_revision: Union[str, None] = "610a0633a584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_buildings", sa.Column("build_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "user_buildings", "buildings", ["build_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("user_buildings", "build_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_buildings",
        sa.Column("build_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_buildings", type_="foreignkey")
    op.drop_column("user_buildings", "build_id")
    # ### end Alembic commands ###
