"""empty message

Revision ID: 58679fc0759f
Revises: 1a50cb18f568
Create Date: 2025-01-02 18:00:40.851157

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "58679fc0759f"
down_revision: Union[str, None] = "1a50cb18f568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
