"""empty message

Revision ID: 622943a100a2
Revises: 1d83c89ce167
Create Date: 2025-01-04 15:57:28.832353

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "622943a100a2"
down_revision: Union[str, None] = "1d83c89ce167"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buildings", sa.Column("icon_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buildings", "icon_url")
    # ### end Alembic commands ###
