"""empty message

Revision ID: d2e801b1ee55
Revises: 0b54b2e996f9
Create Date: 2025-01-05 01:07:19.923294

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2e801b1ee55"
down_revision: Union[str, None] = "0b54b2e996f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_referals",
        sa.Column("referer_id", sa.Integer(), nullable=False),
        sa.Column("referal_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["referal_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("referals", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "referals")
    op.drop_table("user_referals")
    # ### end Alembic commands ###
