"""empty message

Revision ID: d87f6ad9a900
Revises: 89bf7b6ada6f
Create Date: 2025-01-02 15:31:15.783003

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d87f6ad9a900"
down_revision: Union[str, None] = "89bf7b6ada6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_building", "user_buildings", ["user_id", "build_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_building", "user_buildings", type_="unique")
    # ### end Alembic commands ###
