"""empty message

Revision ID: e5885b87710c
Revises: e64add6f3cd8
Create Date: 2025-01-05 14:37:09.689724

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5885b87710c"
down_revision: Union[str, None] = "e64add6f3cd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_referals", "user_referals", ["referer_id", "referal_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_referals", "user_referals", type_="unique")
    # ### end Alembic commands ###
